### ISSUE TITLE
How to populate PERSON.location_id

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Themis#101]
# How to populate the location_id field in the PERSON table

## CDM or THEMIS convention?
THEMIS

## Is this a general convention?
No

## Summary of issues

- How should the location_id be used to represent the location of a person?
- What level of information should be included when modeling the person's location?

## Summary of answer

- The location_id in the PERSON table should represent the most granular level of information available for the person's home address, or where they live the majority of the time. 
- This could represent anything from postal code or parts thereof, state, or county for example. Since many databases contain de-identified data, it is common that the precision of the location is reduced to prevent re-identification.

## Related links

- [Put any links you have found related to this convention
](https://ohdsi.github.io/CommonDataModel/cdm54.html#person)

## Other comments/notes

NA

**Comment by MelaniePhilofsky** [comment]
## Issue # and location
NA

## Issue summary
How should the location_id be used to represent the location of a person?
What level of information should be included when modeling the person's location?

## Convention type
Table

## CDM table
Person

## CDM field
location_id

## Links to issue discussion


## Provenance of data
All

## The ratified convention
The location_id in the PERSON table should represent the most granular level of information available for the person's home address, or where they live the majority of the time.

This could represent anything from postal code or parts thereof, state, or county for example. Since many databases contain de-identified data, it is common that the precision of the location is reduced to prevent re-identification.

## Date of ratification/published


## Downstream implications
No

## Link to DQD check

Format as follows:
Yes - [isForeignKey](https://ohdsi.github.io/DataQualityDashboard/articles/checks/isForeignKey.html).

## Related conventions/further information


**#Tags**
Person, location

**Comment by clairblacketer** [comment]
Opened #115
