### ISSUE TITLE
What should be done with patient reported drugs or conditions

### ISSUE THREAD

**Issue by jiawei-qian** [OHDSI/Themis#174]
# What should be done with patient reported drugs or conditions

## CDM or THEMIS convention?
THEMIS

## Table or Field level?
Field

## Is this a general convention?
No

## Summary of issues
1. What should be done with patient reported drugs or conditions?

## Summary of answer
1. Eric Voss:
**RECOMMENDATION**
Patient reported data recommendation should land in the appropriate domain table (e.g. if a patient reports they had lymphoma it should land in the CONDITION_OCCURRENCE table. These data should be strongly typed so that it easily known which records are patient reported. Use type **32865-"Patient self-report"** to identify these records.

**NEXT STEPS**
Add into Conventions: https://ohdsi.github.io/CommonDataModel/dataModelConventions.html#Data_Model_Conventions

## Related links
OHDSI Forum (Patient-Reported Drugs and Conditions): https://forums.ohdsi.org/t/patient-reported-drugs-and-conditions/3152/28
Themis GitHub: https://github.com/OHDSI/Themis/issues/25
ATHENA link: https://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&standardConcept=Standard&page=1&pageSize=15&query=patient

## Other comments/notes
1. In the OHDSI Forum post, Clair agreed with Erica's recommendation. And gave one example.
![Image](https://github.com/OHDSI/Themis/assets/84256452/21494c8f-2002-4fe2-b09a-d759f78c5937)
@clairblacketer , I am not sure for patient reported history of disease. Whether we need to also create concept 35610328 for “B-cell Hodgkin Lymphoma” in CONDITION_OCCURRENCE table? Maybe we need to make sure if the patient still has this disease when he reports the disease. If not, we can only create a record in OBSERVATION table for concept 43021273 (“History of Hodgkin’s Lymphoma”).

2. In the THEMIS issue https://github.com/OHDSI/Themis/issues/25, Melanie gave a link for patient reported data.
https://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&standardConcept=Standard&page=1&pageSize=15&query=patient
![Image](https://github.com/OHDSI/Themis/assets/84256452/080726a0-8afd-44bf-9a18-16d4e6df4f2a)
@MelaniePhilofsky , When open the link, it shows 9 concepts. I guess the first one (32865: Patient self-report) is the concept we want for patient reported drugs/conditions?

**Comment by clairblacketer** [comment]
Thanks @jiawei-qian, since this is already an accepted Themis issue we should make sure it is in the repository.

**Comment by MelaniePhilofsky** [comment]
## Issue # and location
For this ratified convention, the issue number given when the issue was created by GitHub. Was this a CDM issue, Themis issue, found in CDM documentation or found on the forum?

Format as follows:
- [Themis issue #25](https://github.com/OHDSI/Themis/issues/25)


## Issue summary
What should be done with patient reported clinical events?

## Convention type
Global 

## CDM table
NA

## CDM field
All *_type_concept_id fields in the CDM

## Links to issue discussion
Links to location of discussion on forums, CDM GitHub, Themis GitHub, etc.

Format as follows:
- [OHDSI Forums discussion](https://forums.ohdsi.org/t/patient-reported-drugs-and-conditions/3152/28)
- [Themis issue #25](hhttps://github.com/OHDSI/Themis/issues/25)   

## Provenance of data
EHR

## The ratified convention
Patient reported data should be inserted into the appropriate domain table (e.g. if a patient reports they had lymphoma, it should be inserted into the CONDITION_OCCURRENCE table or if a patient reports using ibuprofen, it should be inserted into the DRUG_EXPOSURE table). Use concept_id = 32865, "Patient self-report" to identify these records.

## Date of ratification/published
June 5, 2018

## Downstream implications
NO

## Link to DQD check
NA

## Related conventions/further information

**#Tags**
patient_reported, self_reported, home_med,

**Comment by clairblacketer** [comment]
@MelaniePhilofsky yes I think that makes the most sense since we now only have one type concept vocabulary
